export const BEATGRID_TOLERANCE_OK_MS = 10
export const BEATGRID_TOLERANCE_WARNING_MS = 50
export const MIN_BEATS_FOR_ANALYSIS = 10
export const VARIABLE_BPM_SKIP_THRESHOLD_PCT = 5.0
export const GRID_VALIDATION_ERROR_RATIO = 0.3
