export const BPM_TOLERANCE_OK = 0.05
export const BPM_TOLERANCE_WARNING = 0.5
export const BPM_TOLERANCE_ERROR = 2.0
export const VARIABLE_BPM_VARIANCE_THRESHOLD_PCT = 2.0
export const SEGMENT_DURATION_SECONDS = 30
